import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

[font]
size = 16.0

[font.normal]
family = "MesloLGS Nerd Font"

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

# [window]
# decorations = "None"

